CREATE DATABASE project1q3_db;

SHOW DATABASES;

USE project1q3_db;

CREATE TABLE P1Q3T1 (
	prev STRING,
	curr STRING,
	tlnk STRING,
	clnk INT)
	ROW FORMAT DELIMITED
	FIELDS TERMINATED BY '\t';

DESCRIBE P1Q3T1;
	
LOAD DATA LOCAL INPATH '/home/cjen/wikiclick_2012/clickstream-enwiki-2020-12.tsv' INTO TABLE P1Q3T1;

SELECT * FROM P1Q3T1;

INSERT OVERWRITE DIRECTORY '/user/hive/p1q3t1_1'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
SELECT prev, curr,
	   SUM(CASE WHEN tlnk = 'link' THEN 1*clnk ELSE 0 END) AS CLICK_TOTAL,	
	   ROUND(SUM(CASE WHEN tlnk = 'link' THEN 1*clnk ELSE 0 END) / SUM(clnk) * 1.0, 4) AS CLICK_PERCENT, 
	   ROUND(SUM(CASE WHEN tlnk = 'link' THEN 1 ELSE 0 END) / COUNT(*) * 1.0, 4) AS LINK_PERCENT
FROM P1Q3T1 
GROUP BY prev, curr
HAVING prev like '%Hotel%California%' 
ORDER BY CLICK_PERCENT DESC, LINK_PERCENT DESC, CLICK_TOTAL DESC;

--
--
--

INSERT OVERWRITE DIRECTORY '/user/hive/p1q3t1_2'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
SELECT prev, curr,
	   SUM(CASE WHEN tlnk = 'link' THEN 1*clnk ELSE 0 END) AS CLICK_TOTAL,	
	   ROUND(SUM(CASE WHEN tlnk = 'link' THEN 1*clnk ELSE 0 END) / SUM(clnk) * 1.0, 4) AS CLICK_PERCENT, 
	   ROUND(SUM(CASE WHEN tlnk = 'link' THEN 1 ELSE 0 END) / COUNT(*) * 1.0, 4) AS LINK_PERCENT
FROM P1Q3T1 
GROUP BY prev, curr
HAVING prev like '%Hotel%California%' OR curr like '%Hotel%California%'
ORDER BY CLICK_PERCENT DESC, LINK_PERCENT DESC, CLICK_TOTAL DESC;

--
--
--

INSERT OVERWRITE DIRECTORY '/user/hive/p1q3t1_3'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
SELECT prev, curr,
	   SUM(CASE WHEN tlnk = 'link' THEN 1*clnk ELSE 0 END) AS CLICK_TOTAL,	
	   ROUND(SUM(CASE WHEN tlnk = 'link' THEN 1*clnk ELSE 0 END) / SUM(clnk) * 1.0, 4) AS CLICK_PERCENT, 
	   ROUND(SUM(CASE WHEN tlnk = 'link' THEN 1 ELSE 0 END) / COUNT(*) * 1.0, 4) AS LINK_PERCENT
FROM P1Q3T1 
GROUP BY prev, curr
HAVING prev like '%Hotel%California%' OR curr like '%Hotel%California%'
ORDER BY CLICK_TOTAL DESC, CLICK_PERCENT DESC, LINK_PERCENT DESC;
