CREATE DATABASE project1q8_db;

SHOW DATABASES;

USE project1q8_db;

CREATE TABLE P1Q8T1 (
	prev STRING,
	curr STRING,
	tlnk STRING,
	clnk INT)
	ROW FORMAT DELIMITED
	FIELDS TERMINATED BY '\t';

DESCRIBE P1Q8T1;
	
LOAD DATA LOCAL INPATH '/home/cjen/wikiclick_2012/clickstream-enwiki-2020-12.tsv' INTO TABLE P1Q8T1;

SELECT * FROM P1Q8T1;

INSERT OVERWRITE DIRECTORY '/user/hive/p1q8t1_1'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
SELECT prev, curr, 
	   SUM(CASE WHEN tlnk = 'link' THEN 1*clnk ELSE 0 END) AS CLICK_TOTAL,	
	   ROUND(SUM(CASE WHEN tlnk = 'link' THEN 1*clnk ELSE 0 END) / SUM(clnk) * 1.0, 4) AS CLICK_PERCENT, 
	   ROUND(SUM(CASE WHEN tlnk = 'link' THEN 1 ELSE 0 END) / COUNT(*) * 1.0, 4) AS LINK_PERCENT
FROM P1Q8T1
GROUP BY prev, curr 
ORDER BY CLICK_TOTAL DESC, CLICK_PERCENT DESC, LINK_PERCENT DESC;

CREATE TABLE P1Q8T2 (
	domain_code STRING,
	page_title STRING,
	count_views INT,
	total_response_size INT)
	ROW FORMAT DELIMITED
	FIELDS TERMINATED BY ' ';
	
DESCRIBE P1Q8T2;

LOAD DATA LOCAL INPATH '/home/cjen/pageviews_2012/pageviews-20201229_full.tsv' INTO TABLE P1Q8T2;

SELECT * FROM P1Q8T2;

INSERT OVERWRITE DIRECTORY '/user/hive/p1q8t2_1'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
SELECT page_title, SUM(count_views) AS total_views
FROM P1Q8T2
WHERE domain_code LIKE 'en%'
GROUP BY page_title
ORDER BY total_views DESC;

CREATE TABLE P1Q8T3 (
	ptitle STRING,
	tviews INT)
	ROW FORMAT DELIMITED
	FIELDS TERMINATED BY '\t';

DESCRIBE P1Q8T3;

LOAD DATA LOCAL INPATH '/home/cjen/wikiclick_2012/p1q8t2_1.tsv' INTO TABLE P1Q8T3;

SELECT * FROM P1Q8T3;

CREATE TABLE P1Q8T4 (
	prev STRING,
	curr STRING,
	tlnk INT,
	rtck DOUBLE,
	rlnk DOUBLE,
	ptitle STRING,
	tviews INT)
	ROW FORMAT DELIMITED
	FIELDS TERMINATED BY '\t';

-- DROP TABLE P1Q8T4;

DESCRIBE P1Q8T4;

LOAD DATA LOCAL INPATH '/home/cjen/wikiclick_2012/p1q8t1_1.tsv' INTO TABLE P1Q8T4;

SELECT * FROM P1Q8T4;

INSERT OVERWRITE DIRECTORY '/user/hive/p1q8t3_1'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
SELECT t4.prev, t4.curr, t4.tlnk, t4.rtck, t4.rlnk, t3.ptitle, t3.tviews 
FROM p1q8t4 t4 
JOIN p1q8t3 t3
ON (t4.prev = t3.ptitle);

CREATE TABLE P1Q8T5 (
	prev STRING,
	curr STRING,
	tlnk INT,
	rtck DOUBLE,
	rlnk DOUBLE,
	ptitle STRING,
	tviews INT)
	ROW FORMAT DELIMITED
	FIELDS TERMINATED BY '\t';

DESCRIBE P1Q8T5;

LOAD DATA LOCAL INPATH '/home/cjen/wikiclick_2012/p1q8t3_1.tsv' INTO TABLE P1Q8T5;

SELECT * FROM P1Q8T5;

-- DROP TABLE P1Q8T5;

INSERT OVERWRITE DIRECTORY '/user/hive/p1q8t4_1'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
SELECT prev, curr, tlnk, tviews, ROUND(tlnk / tviews / 31.0 * 1.0, 2) AS CLICK_VIEW_PERCENT, ptitle, rtck, rlnk
FROM P1Q8T5 
ORDER BY CLICK_VIEW_PERCENT DESC, tviews DESC, tlnk DESC;

--INSERT OVERWRITE DIRECTORY '/user/hive/p1q8t5_1'
--ROW FORMAT DELIMITED
--FIELDS TERMINATED BY '\t'
--SELECT ptitle, ROUND(SUM(tlnk) / SUM(tviews) / 31.0 * 1.0, 2) AS CLICK_VIEW_PERCENT
--FROM P1Q8T5 
--GROUP BY ptitle
--ORDER BY CLICK_VIEW_PERCENT DESC;

INSERT OVERWRITE DIRECTORY '/user/hive/p1q8t6_1'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
SELECT curr, ROUND(SUM(tlnk) / SUM(tviews) / 31.0 * 1.0, 2) AS CLICK_VIEW_PERCENT
FROM P1Q8T5 
GROUP BY curr
ORDER BY CLICK_VIEW_PERCENT DESC;

INSERT OVERWRITE DIRECTORY '/user/hive/p1q8t7_1'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
SELECT curr, ROUND(SUM(tlnk) / SUM(tviews) / 31.0 * 1.0, 2) AS CLICK_VIEW_PERCENT
FROM P1Q8T5 
GROUP BY curr
HAVING curr like '%Hotel%California%'
ORDER BY CLICK_VIEW_PERCENT DESC;

INSERT OVERWRITE DIRECTORY '/user/hive/p1q8t8_1'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
SELECT prev, ROUND(SUM(tlnk) / SUM(tviews) / 31.0 * 1.0, 2) AS CLICK_VIEW_PERCENT
FROM P1Q8T5 
GROUP BY prev
HAVING prev like '%Hotel%California%'
ORDER BY CLICK_VIEW_PERCENT DESC;

INSERT OVERWRITE DIRECTORY '/user/hive/p1q8t9_1'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
SELECT prev, curr, ROUND(SUM(tlnk) / SUM(tviews) / 31.0 * 1.0, 2) AS CLICK_VIEW_PERCENT
FROM P1Q8T5 
GROUP BY prev, curr
HAVING prev like '%Hotel%California%' OR curr like '%Hotel%California%'
ORDER BY CLICK_VIEW_PERCENT DESC;

