CREATE DATABASE project1q7_db;

SHOW DATABASES;

USE project1q7_db;

CREATE TABLE P1Q7T1 (
	domain_code STRING,
	page_title STRING,
	count_views INT,
	total_response_size INT)
	ROW FORMAT DELIMITED
	FIELDS TERMINATED BY ' ';

DESCRIBE P1Q7T1;

LOAD DATA LOCAL INPATH '/home/cjen/pageviews_2012/pageviews-20201229.tsv' INTO TABLE P1Q7T1;

SELECT * FROM P1Q7T1;

-- DROP TABLE P1Q7T1;

CREATE TABLE P1Q7T2 (
	prev STRING,
	curr STRING,
	tlnk INT,
	rtck DOUBLE,
	rlnk DOUBLE)
	ROW FORMAT DELIMITED
	FIELDS TERMINATED BY '\t';

DESCRIBE P1Q7T2;
	
LOAD DATA LOCAL INPATH '/home/cjen/wikiclick_2012/p1q2t2_8.tsv' INTO TABLE P1Q7T2;

SELECT * FROM P1Q7T2;

-- DROP TABLE P1Q7T2;

INSERT OVERWRITE DIRECTORY '/user/hive/p1q7t1_1'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
SELECT page_title, SUM(count_views) AS total_views
FROM P1Q7T1
WHERE domain_code LIKE 'en%'
GROUP BY page_title
ORDER BY total_views DESC;

CREATE TABLE P1Q7T3 (
	ptitle STRING,
	tviews INT)
	ROW FORMAT DELIMITED
	FIELDS TERMINATED BY '\t';

DESCRIBE P1Q7T3;

LOAD DATA LOCAL INPATH '/home/cjen/wikiclick_2012/p1q7t1_1.tsv' INTO TABLE P1Q7T3;

SELECT * FROM P1Q7T3;

INSERT OVERWRITE DIRECTORY '/user/hive/p1q7t2_1'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
SELECT t2.prev, t2.curr, t2.tlnk, t2.rtck, t2.rlnk, t3.ptitle, t3.tviews 
FROM p1q7t2 t2 
JOIN p1q7t3 t3
ON (t2.prev = t3.ptitle);

CREATE TABLE P1Q7T4 (
	prev STRING,
	curr STRING,
	tlnk INT,
	rtck DOUBLE,
	rlnk DOUBLE,
	ptitle STRING,
	tviews INT)
	ROW FORMAT DELIMITED
	FIELDS TERMINATED BY '\t';

DESCRIBE P1Q7T4;

LOAD DATA LOCAL INPATH '/home/cjen/wikiclick_2012/p1q7t2_1.tsv' INTO TABLE P1Q7T4;

SELECT * FROM P1Q7T4;

INSERT OVERWRITE DIRECTORY '/user/hive/p1q7t3_1'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
SELECT prev, curr, tlnk, tviews, ROUND(tlnk / tviews / 31.0 * 1.0, 2) AS CLICK_VIEW_PERCENT, ptitle, rtck, rlnk
FROM P1Q7T4 
ORDER BY CLICK_VIEW_PERCENT DESC, tviews DESC, tlnk DESC;

INSERT OVERWRITE DIRECTORY '/user/hive/p1q7t4_1'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
SELECT prev, ROUND(SUM(tlnk) / SUM(tviews) / 31.0 * 1.0, 2) AS CLICK_VIEW_PERCENT
FROM P1Q7T4 
GROUP BY prev
ORDER BY CLICK_VIEW_PERCENT DESC;

INSERT OVERWRITE DIRECTORY '/user/hive/p1q7t5_1'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
SELECT curr, ROUND(SUM(tlnk) / SUM(tviews) / 31.0 * 1.0, 2) AS CLICK_VIEW_PERCENT
FROM P1Q7T4 
GROUP BY curr
ORDER BY CLICK_VIEW_PERCENT DESC;




